public with sharing class CaseTriggerHelper {
    
    /*public CaseTriggerHelper() {

    }*/
/*
    public static void createNewSubCase(list<Case> cases){

        list<Case> newCases = new list<Case>();
        for(Case theCase: cases){
            Case newCase = new Case();
            newCase.Vehicle__c = theCase.Vehicle__c;
            //theCase
            newCases.add(newCase);
        }
        if(newCases.size() > 0){
            insert newCases;
        }
    }
    */
}